### ISSUE TITLE
Babel 7 issues checklist

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/datx#109]
* [x] Prop is undefined - Fixed in https://github.com/infinum/datx/commit/d681f69634ba0f5b15a3b9fac6629cbe01886771
* [x] Prop decorator not working - Fixed in https://github.com/infinum/datx/commit/d681f69634ba0f5b15a3b9fac6629cbe01886771
* [x] Assignment to indirect reference - In some situations Babel is trying to init the field value that shouldn't be changed - Fixed in https://github.com/infinum/datx/commit/d681f69634ba0f5b15a3b9fac6629cbe01886771
* [x] Undefined views - Similar to "Prop is undefined", the prop initialisation is overriding the datx value - Fixed with `@view` decorator in https://github.com/infinum/datx/commit/9464ea31478d55c94342bc913c3f4ae1ef7c62fb
