### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/datx#232]
# v2
ETA: ASAP

- [ ] #230 - Expose request params in the interceptor
- [ ] #231 - Move the npm packages to the `@datx` scope
- [ ] Finish the docs

# v3
ETA: 🤷 

- [ ] Refactor networking to make it more generic
- [ ] Add `@datx/react` that integrates `@datx/networking` with `swr`
- [ ] Refactor `@datx/jsonapi-angular` to make it more generic `@datx/angular` and more in line with `@datx/react`

**Comment by isBatak** [comment]
@DarkoKukovec any updates regarding v3 and v4? :D

**Comment by DarkoKukovec** [comment]
@isBatak I've updated the roadmap. v3 is published as a beta and I'm waiting for feedback.
